name: Build & Push Docker Image

on:
  push:
    branches:
      - master  # Run workflow on push to master
    tags:
      - v*      # Run workflow on versioned tags (e.g., v1.0.0)
  pull_request:
    branches:
      - master  # Run workflow on PRs to master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up JDK for Maven Build
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      # Cache Maven Dependencies for Faster Builds
      - name: Cache Maven Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: maven-

      # Build the JAR file using Maven
      - name: Build JAR with Maven
        run: mvn clean package -DskipTests

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and Tag Docker Image
      - name: 🛠️ Build Docker Image
        run: |
          ls -la  # Debugging step: List files in the working directory
          docker build -t ${{ secrets.DOCKER_USERNAME }}/co2-calculator:latest .

      # Push Docker Image to Docker Hub
      - name: Push Docker Image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/co2-calculator:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/co2-calculator:${{ github.run_number }}
